### ISSUE TITLE
doc file preview error

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-seafile#7]
Offer ID: cmjj00043548
version: 3.7.5-new (but it is 3.7.4 actually)

![image](https://user-images.githubusercontent.com/16741975/104844562-e49def00-590b-11eb-9da0-0ebf59ecf6d0.png)

**Comment by chendelin1982** [comment]
Is /data/wwwroot/seafile/connect-onlyoffice.conf not correct?

**Comment by chendelin1982** [comment]
3.7.4 need to restart Docker, but new image have not error

**Comment by chendelin1982** [comment]
![Uploading image.png…]()

**Comment by chendelin1982** [comment]
I use Seafile8.0.4 community, connect OnlyOffice by http (not https), the error below
![image](https://user-images.githubusercontent.com/16741975/116044773-e5c97f80-a6a3-11eb-9467-f96dad284f6d.png)

then, I modify onlyofficedocumentserver, set  - JWT_ENABLED=flase, and I can edit docs 
```
version: '3'
services:     
  onlyoffice-document-server:
    container_name: onlyoffice-docs
    image: onlyoffice/documentserver:6.0.2
    stdin_open: true
    tty: true
    restart: always
    environment:
     - JWT_ENABLED=flase
     - JWT_SECRET=jwt_secret
     - JWT_HEADER=AuthorizationJwt
    ports:
     - '9003:80'
    expose:
      - '80'
      - '443'
    volumes:
       - ./document_data:/var/www/onlyoffice/Data
       - ./document_log:/var/log/onlyoffice
       - ./document_fonts:/usr/share/fonts/truetype/custom
       - ./document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
```

![image](https://user-images.githubusercontent.com/16741975/116063394-7eb5c600-a6b7-11eb-918d-8b47b500440a.png)
